export const themes = {
  'amber-minimal': {
    name: 'Amber Minimal',
    colors: {
      primary: '#f59e0b',
      'primary-foreground': '#000000',
      secondary: '#404040',
      'secondary-foreground': '#ffffff',
      accent: '#92400e',
      'accent-foreground': '#ffffff',
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#1a1a1a',
      'card-foreground': '#ffffff',
      popover: '#1a1a1a',
      'popover-foreground': '#ffffff',
      muted: '#404040',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#404040',
      input: '#262626',
      ring: '#f59e0b',
    }
  },
  'amethyst-haze': {
    name: 'Amethyst Haze',
    colors: {
      primary: '#a995c9',
      'primary-foreground': '#000000',
      secondary: '#5a5370',
      'secondary-foreground': '#ffffff',
      accent: '#8b7aa3',
      'accent-foreground': '#ffffff',
      background: '#0f0e14',
      foreground: '#ffffff',
      card: '#1a1823',
      'card-foreground': '#ffffff',
      popover: '#1a1823',
      'popover-foreground': '#ffffff',
      muted: '#302c40',
      'muted-foreground': '#ffffff',
      destructive: '#e57373',
      'destructive-foreground': '#000000',
      border: '#302c40',
      input: '#2a273a',
      ring: '#a995c9',
    }
  },
  'bold-tech': {
    name: 'Bold Tech',
    colors: {
      primary: '#8b5cf6',
      'primary-foreground': '#ffffff',
      secondary: '#1e1b4b',
      'secondary-foreground': '#ffffff',
      accent: '#4338ca',
      'accent-foreground': '#ffffff',
      background: '#050409',
      foreground: '#ffffff',
      card: '#0f0c1a',
      'card-foreground': '#ffffff',
      popover: '#0f0c1a',
      'popover-foreground': '#ffffff',
      muted: '#2e1065',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#2e1065',
      input: '#1e1b4b',
      ring: '#8b5cf6',
    }
  },
  'bubblegum': {
    name: 'Bubblegum',
    colors: {
      primary: '#fbe2a7',
      'primary-foreground': '#000000',
      secondary: '#e4a2b1',
      'secondary-foreground': '#000000',
      accent: '#c67b96',
      'accent-foreground': '#ffffff',
      background: '#0a0508',
      foreground: '#ffffff',
      card: '#12242e',
      'card-foreground': '#ffffff',
      popover: '#12242e',
      'popover-foreground': '#ffffff',
      muted: '#324859',
      'muted-foreground': '#ffffff',
      destructive: '#e35ea4',
      'destructive-foreground': '#ffffff',
      border: '#324859',
      input: '#20333d',
      ring: '#50afb6',
    }
  },
  'caffeine': {
    name: 'Caffeine',
    colors: {
      primary: '#ffe0c2',
      'primary-foreground': '#000000',
      secondary: '#654321',
      'secondary-foreground': '#ffffff',
      accent: '#8b4513',
      'accent-foreground': '#ffffff',
      background: '#070707',
      foreground: '#ffffff',
      card: '#111111',
      'card-foreground': '#ffffff',
      popover: '#111111',
      'popover-foreground': '#ffffff',
      muted: '#484848',
      'muted-foreground': '#ffffff',
      destructive: '#e54d2e',
      'destructive-foreground': '#ffffff',
      border: '#484848',
      input: '#2a2a2a',
      ring: '#ffe0c2',
    }
  },
  'candyland': {
    name: 'Candyland',
    colors: {
      primary: '#ff99cc',
      'primary-foreground': '#000000',
      secondary: '#33cc33',
      'secondary-foreground': '#000000',
      accent: '#87ceeb',
      'accent-foreground': '#000000',
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#1a1d23',
      'card-foreground': '#ffffff',
      popover: '#1a1d23',
      'popover-foreground': '#ffffff',
      muted: '#444444',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#444444',
      input: '#2f3436',
      ring: '#ff99cc',
    }
  },
  'catppuccin': {
    name: 'Catppuccin',
    colors: {
      primary: '#cba6f7',
      'primary-foreground': '#000000',
      secondary: '#585b70',
      'secondary-foreground': '#ffffff',
      accent: '#89dceb',
      'accent-foreground': '#000000',
      background: '#0c0c14',
      foreground: '#ffffff',
      card: '#181825',
      'card-foreground': '#ffffff',
      popover: '#181825',
      'popover-foreground': '#ffffff',
      muted: '#313244',
      'muted-foreground': '#ffffff',
      destructive: '#f38ba8',
      'destructive-foreground': '#000000',
      border: '#313244',
      input: '#1e1e2e',
      ring: '#cba6f7',
    }
  },
  'claude': {
    name: 'Claude',
    colors: {
      primary: '#d97757',
      'primary-foreground': '#ffffff',
      secondary: '#52514a',
      'secondary-foreground': '#ffffff',
      accent: '#6b5b47',
      'accent-foreground': '#ffffff',
      background: '#0a0a09',
      foreground: '#ffffff',
      card: '#262624',
      'card-foreground': '#ffffff',
      popover: '#262624',
      'popover-foreground': '#ffffff',
      muted: '#52514a',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#3e3e38',
      input: '#30302e',
      ring: '#207fde',
    }
  },
  'claymorphism': {
    name: 'Claymorphism',
    colors: {
      primary: '#818cf8',
      'primary-foreground': '#ffffff',
      secondary: '#3a3633',
      'secondary-foreground': '#ffffff',
      accent: '#f59e0b',
      'accent-foreground': '#000000',
      background: '#0a0907',
      foreground: '#ffffff',
      card: '#1e1b18',
      'card-foreground': '#ffffff',
      popover: '#1e1b18',
      'popover-foreground': '#ffffff',
      muted: '#4a453f',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#4a453f',
      input: '#3a3633',
      ring: '#818cf8',
    }
  },
  'cosmic-blue': {
    name: 'Cosmic Blue',
    colors: {
      primary: '#00bfff',
      'primary-foreground': '#000000',
      secondary: '#1e3a8a',
      'secondary-foreground': '#ffffff',
      accent: '#4169e1',
      'accent-foreground': '#ffffff',
      background: '#020817',
      foreground: '#ffffff',
      card: '#0f172a',
      'card-foreground': '#ffffff',
      popover: '#0f172a',
      'popover-foreground': '#ffffff',
      muted: '#1e3a8a',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#1e3a8a',
      input: '#1e293b',
      ring: '#00bfff',
    }
  },
  'cyberpunk': {
    name: 'Cyberpunk',
    colors: {
      primary: '#ff007f',
      'primary-foreground': '#ffffff',
      secondary: '#7c3aed',
      'secondary-foreground': '#ffffff',
      accent: '#06ffa5',
      'accent-foreground': '#000000',
      background: '#000814',
      foreground: '#ffffff',
      card: '#001d3d',
      'card-foreground': '#ffffff',
      popover: '#001d3d',
      'popover-foreground': '#ffffff',
      muted: '#003566',
      'muted-foreground': '#ffffff',
      destructive: '#ff006e',
      'destructive-foreground': '#ffffff',
      border: '#003566',
      input: '#001845',
      ring: '#ff007f',
    }
  },
  'emerald-forest': {
    name: 'Emerald Forest',
    colors: {
      primary: '#10b981',
      'primary-foreground': '#ffffff',
      secondary: '#064e3b',
      'secondary-foreground': '#ffffff',
      accent: '#059669',
      'accent-foreground': '#ffffff',
      background: '#022c22',
      foreground: '#ffffff',
      card: '#064e3b',
      'card-foreground': '#ffffff',
      popover: '#064e3b',
      'popover-foreground': '#ffffff',
      muted: '#065f46',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#065f46',
      input: '#047857',
      ring: '#10b981',
    }
  },
  'golden-sunset': {
    name: 'Golden Sunset',
    colors: {
      primary: '#f59e0b',
      'primary-foreground': '#000000',
      secondary: '#ea580c',
      'secondary-foreground': '#ffffff',
      accent: '#dc2626',
      'accent-foreground': '#ffffff',
      background: '#451a03',
      foreground: '#ffffff',
      card: '#7c2d12',
      'card-foreground': '#ffffff',
      popover: '#7c2d12',
      'popover-foreground': '#ffffff',
      muted: '#9a3412',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#9a3412',
      input: '#ea580c',
      ring: '#f59e0b',
    }
  },
  'hacker-green': {
    name: 'Hacker Green',
    colors: {
      primary: '#00ff00',
      'primary-foreground': '#000000',
      secondary: '#008000',
      'secondary-foreground': '#ffffff',
      accent: '#32cd32',
      'accent-foreground': '#000000',
      background: '#000000',
      foreground: '#ffffff',
      card: '#0a0a0a',
      'card-foreground': '#ffffff',
      popover: '#0a0a0a',
      'popover-foreground': '#ffffff',
      muted: '#1a1a1a',
      'muted-foreground': '#ffffff',
      destructive: '#ff0000',
      'destructive-foreground': '#ffffff',
      border: '#008000',
      input: '#003300',
      ring: '#00ff00',
    }
  },
  'lavender-mist': {
    name: 'Lavender Mist',
    colors: {
      primary: '#c084fc',
      'primary-foreground': '#000000',
      secondary: '#7c3aed',
      'secondary-foreground': '#ffffff',
      accent: '#a855f7',
      'accent-foreground': '#ffffff',
      background: '#1e1b4b',
      foreground: '#ffffff',
      card: '#312e81',
      'card-foreground': '#ffffff',
      popover: '#312e81',
      'popover-foreground': '#ffffff',
      muted: '#4338ca',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#4338ca',
      input: '#3730a3',
      ring: '#c084fc',
    }
  },
  'monochrome-light': {
    name: 'Monochrome Light',
    colors: {
      primary: '#000000',
      'primary-foreground': '#ffffff',
      secondary: '#666666',
      'secondary-foreground': '#ffffff',
      accent: '#333333',
      'accent-foreground': '#ffffff',
      background: '#ffffff',
      foreground: '#000000',
      card: '#f8fafc',
      'card-foreground': '#000000',
      popover: '#f8fafc',
      'popover-foreground': '#000000',
      muted: '#f1f5f9',
      'muted-foreground': '#000000',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#ffffff',
      ring: '#000000',
    }
  },
  'monochrome-dark': {
    name: 'Monochrome Dark',
    colors: {
      primary: '#ffffff',
      'primary-foreground': '#000000',
      secondary: '#666666',
      'secondary-foreground': '#ffffff',
      accent: '#cccccc',
      'accent-foreground': '#000000',
      background: '#000000',
      foreground: '#ffffff',
      card: '#0a0a0a',
      'card-foreground': '#ffffff',
      popover: '#0a0a0a',
      'popover-foreground': '#ffffff',
      muted: '#1a1a1a',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#333333',
      input: '#1a1a1a',
      ring: '#ffffff',
    }
  },
  'nature': {
    name: 'Nature',
    colors: {
      primary: '#22c55e',
      'primary-foreground': '#000000',
      secondary: '#16a34a',
      'secondary-foreground': '#ffffff',
      accent: '#84cc16',
      'accent-foreground': '#000000',
      background: '#052e16',
      foreground: '#ffffff',
      card: '#14532d',
      'card-foreground': '#ffffff',
      popover: '#14532d',
      'popover-foreground': '#ffffff',
      muted: '#166534',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#166534',
      input: '#15803d',
      ring: '#22c55e',
    }
  },
  'neon-nights': {
    name: 'Neon Nights',
    colors: {
      primary: '#ff0080',
      'primary-foreground': '#ffffff',
      secondary: '#8000ff',
      'secondary-foreground': '#ffffff',
      accent: '#00ffff',
      'accent-foreground': '#000000',
      background: '#000012',
      foreground: '#ffffff',
      card: '#1a003a',
      'card-foreground': '#ffffff',
      popover: '#1a003a',
      'popover-foreground': '#ffffff',
      muted: '#2d0054',
      'muted-foreground': '#ffffff',
      destructive: '#ff4081',
      'destructive-foreground': '#ffffff',
      border: '#8000ff',
      input: '#1a0033',
      ring: '#ff0080',
    }
  },
  'ocean-blue': {
    name: 'Ocean Blue',
    colors: {
      primary: '#0ea5e9',
      'primary-foreground': '#ffffff',
      secondary: '#0369a1',
      'secondary-foreground': '#ffffff',
      accent: '#0284c7',
      'accent-foreground': '#ffffff',
      background: '#0c4a6e',
      foreground: '#ffffff',
      card: '#075985',
      'card-foreground': '#ffffff',
      popover: '#075985',
      'popover-foreground': '#ffffff',
      muted: '#0369a1',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#0369a1',
      input: '#0284c7',
      ring: '#0ea5e9',
    }
  },
  'pastel-dream': {
    name: 'Pastel Dream',
    colors: {
      primary: '#f472b6',
      'primary-foreground': '#ffffff',
      secondary: '#a78bfa',
      'secondary-foreground': '#ffffff',
      accent: '#60a5fa',
      'accent-foreground': '#ffffff',
      background: '#fef7ff',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      muted: '#f3f4f6',
      'muted-foreground': '#000000',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#ffffff',
      ring: '#f472b6',
    }
  },
  'purple-haze': {
    name: 'Purple Haze',
    colors: {
      primary: '#a855f7',
      'primary-foreground': '#ffffff',
      secondary: '#7c3aed',
      'secondary-foreground': '#ffffff',
      accent: '#8b5cf6',
      'accent-foreground': '#ffffff',
      background: '#2e1065',
      foreground: '#ffffff',
      card: '#4c1d95',
      'card-foreground': '#ffffff',
      popover: '#4c1d95',
      'popover-foreground': '#ffffff',
      muted: '#5b21b6',
      'muted-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#5b21b6',
      input: '#6d28d9',
      ring: '#a855f7',
    }
  },
  'retro-wave': {
    name: 'Retro Wave',
    colors: {
      primary: '#ff006e',
      'primary-foreground': '#ffffff',
      secondary: '#8338ec',
      'secondary-foreground': '#ffffff',
      accent: '#3a86ff',
      'accent-foreground': '#ffffff',
      background: '#0a0015',
      foreground: '#ffffff',
      card: '#1a0033',
      'card-foreground': '#ffffff',
      popover: '#1a0033',
      'popover-foreground': '#ffffff',
      muted: '#2d004f',
      'muted-foreground': '#ffffff',
      destructive: '#ff006e',
      'destructive-foreground': '#ffffff',
      border: '#8338ec',
      input: '#2a1054',
      ring: '#ff006e',
    }
  },
  'rose-gold': {
    name: 'Rose Gold',
    colors: {
      primary: '#f43f5e',
      'primary-foreground': '#ffffff',
      secondary: '#be185d',
      'secondary-foreground': '#ffffff',
      accent: '#e11d48',
      'accent-foreground': '#ffffff',
      background: '#4c0519',
      foreground: '#ffffff',
      card: '#881337',
      'card-foreground': '#ffffff',
      popover: '#881337',
      'popover-foreground': '#ffffff',
      muted: '#9f1239',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#9f1239',
      input: '#be185d',
      ring: '#f43f5e',
    }
  },
  'sakura': {
    name: 'Sakura',
    colors: {
      primary: '#f472b6',
      'primary-foreground': '#ffffff',
      secondary: '#ec4899',
      'secondary-foreground': '#ffffff',
      accent: '#db2777',
      'accent-foreground': '#ffffff',
      background: '#fdf2f8',
      foreground: '#000000',
      card: '#fef7ff',
      'card-foreground': '#000000',
      popover: '#fef7ff',
      'popover-foreground': '#000000',
      muted: '#fce7f3',
      'muted-foreground': '#000000',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#f3e8ff',
      input: '#ffffff',
      ring: '#f472b6',
    }
  },
  'sepia-vintage': {
    name: 'Sepia Vintage',
    colors: {
      primary: '#92400e',
      'primary-foreground': '#ffffff',
      secondary: '#78350f',
      'secondary-foreground': '#ffffff',
      accent: '#a16207',
      'accent-foreground': '#ffffff',
      background: '#451a03',
      foreground: '#ffffff',
      card: '#78350f',
      'card-foreground': '#ffffff',
      popover: '#78350f',
      'popover-foreground': '#ffffff',
      muted: '#92400e',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#a16207',
      input: '#92400e',
      ring: '#f59e0b',
    }
  },
  'soft-minimalist': {
    name: 'Soft Minimalist',
    colors: {
      primary: '#374151',
      'primary-foreground': '#ffffff',
      secondary: '#6b7280',
      'secondary-foreground': '#ffffff',
      accent: '#4b5563',
      'accent-foreground': '#ffffff',
      background: '#f9fafb',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      muted: '#f3f4f6',
      'muted-foreground': '#000000',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#ffffff',
      ring: '#374151',
    }
  },
  'sunset-orange': {
    name: 'Sunset Orange',
    colors: {
      primary: '#ea580c',
      'primary-foreground': '#ffffff',
      secondary: '#dc2626',
      'secondary-foreground': '#ffffff',
      accent: '#f59e0b',
      'accent-foreground': '#000000',
      background: '#431407',
      foreground: '#ffffff',
      card: '#7c2d12',
      'card-foreground': '#ffffff',
      popover: '#7c2d12',
      'popover-foreground': '#ffffff',
      muted: '#9a3412',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#9a3412',
      input: '#ea580c',
      ring: '#ea580c',
    }
  },
  'synthwave': {
    name: 'Synthwave',
    colors: {
      primary: '#ff00ff',
      'primary-foreground': '#000000',
      secondary: '#00ffff',
      'secondary-foreground': '#000000',
      accent: '#ffff00',
      'accent-foreground': '#000000',
      background: '#0a0014',
      foreground: '#ffffff',
      card: '#2d0033',
      'card-foreground': '#ffffff',
      popover: '#2d0033',
      'popover-foreground': '#ffffff',
      muted: '#4d0066',
      'muted-foreground': '#ffffff',
      destructive: '#ff0080',
      'destructive-foreground': '#ffffff',
      border: '#8000ff',
      input: '#1a001f',
      ring: '#ff00ff',
    }
  },
  'terminal-green': {
    name: 'Terminal Green',
    colors: {
      primary: '#22c55e',
      'primary-foreground': '#000000',
      secondary: '#16a34a',
      'secondary-foreground': '#ffffff',
      accent: '#15803d',
      'accent-foreground': '#ffffff',
      background: '#000000',
      foreground: '#ffffff',
      card: '#0a0a0a',
      'card-foreground': '#ffffff',
      popover: '#0a0a0a',
      'popover-foreground': '#ffffff',
      muted: '#1a1a1a',
      'muted-foreground': '#ffffff',
      destructive: '#ff0000',
      'destructive-foreground': '#ffffff',
      border: '#22c55e',
      input: '#001100',
      ring: '#22c55e',
    }
  },
  'tropical-sunset': {
    name: 'Tropical Sunset',
    colors: {
      primary: '#f97316',
      'primary-foreground': '#ffffff',
      secondary: '#dc2626',
      'secondary-foreground': '#ffffff',
      accent: '#eab308',
      'accent-foreground': '#000000',
      background: '#431407',
      foreground: '#ffffff',
      card: '#7c2d12',
      'card-foreground': '#ffffff',
      popover: '#7c2d12',
      'popover-foreground': '#ffffff',
      muted: '#9a3412',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#9a3412',
      input: '#ea580c',
      ring: '#f97316',
    }
  },
  'vintage-paper': {
    name: 'Vintage Paper',
    colors: {
      primary: '#92400e',
      'primary-foreground': '#ffffff',
      secondary: '#a16207',
      'secondary-foreground': '#ffffff',
      accent: '#ca8a04',
      'accent-foreground': '#000000',
      background: '#fefdf8',
      foreground: '#000000',
      card: '#fffbeb',
      'card-foreground': '#000000',
      popover: '#fffbeb',
      'popover-foreground': '#000000',
      muted: '#fef3c7',
      'muted-foreground': '#000000',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#fde68a',
      input: '#ffffff',
      ring: '#92400e',
    }
  },
  'winter-blue': {
    name: 'Winter Blue',
    colors: {
      primary: '#0ea5e9',
      'primary-foreground': '#ffffff',
      secondary: '#0284c7',
      'secondary-foreground': '#ffffff',
      accent: '#0369a1',
      'accent-foreground': '#ffffff',
      background: '#0c4a6e',
      foreground: '#ffffff',
      card: '#075985',
      'card-foreground': '#ffffff',
      popover: '#075985',
      'popover-foreground': '#ffffff',
      muted: '#0369a1',
      'muted-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#0284c7',
      input: '#0369a1',
      ring: '#0ea5e9',
    }
  },
  'zen-garden': {
    name: 'Zen Garden',
    colors: {
      primary: '#059669',
      'primary-foreground': '#ffffff',
      secondary: '#047857',
      'secondary-foreground': '#ffffff',
      accent: '#065f46',
      'accent-foreground': '#ffffff',
      background: '#f0fdf4',
      foreground: '#000000',
      card: '#ecfdf5',
      'card-foreground': '#000000',
      popover: '#ecfdf5',
      'popover-foreground': '#000000',
      muted: '#d1fae5',
      'muted-foreground': '#000000',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#bbf7d0',
      input: '#ffffff',
      ring: '#059669',
    }
  }
};

export const getTheme = (themeName) => {
  return themes[themeName] || themes['claude'];
};

export const getThemeNames = () => {
  return Object.keys(themes);
}; 