"""new_attempt_with_correct_env_and_models

Revision ID: 2628311cb578
Revises: 
Create Date: 2025-05-18 01:13:29.410219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2628311cb578'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deep_dive_messages', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('topic_stream_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('topic_stream_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('sources',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('query',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('update_frequency',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('detail_level',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=19),
               nullable=False)
        batch_op.alter_column('recency_filter',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.7)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.7)'))
        batch_op.alter_column('recency_filter',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=19),
               nullable=True)
        batch_op.alter_column('detail_level',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('update_frequency',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('query',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('sources',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('topic_stream_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('deep_dive_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('topic_stream_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
