"""refine_topicstream_last_updated_logic

Revision ID: 90f137c451f9
Revises: e2cab5cd23ac
Create Date: 2025-05-19 14:37:09.803298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f137c451f9'
down_revision: Union[str, None] = 'e2cab5cd23ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
