"""add_auto_update_enabled_column_to_topic_streams_properly

Revision ID: e2cab5cd23ac
Revises: 2628311cb578
Create Date: 2025-05-19 12:27:31.430623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cab5cd23ac'
down_revision: Union[str, None] = '2628311cb578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_update_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_streams', schema=None) as batch_op:
        batch_op.drop_column('auto_update_enabled')

    # ### end Alembic commands ###
